In [1]:
# import libraries
import pandas as pd
import requests
pd.set_option('display.max_columns', None)  # so we can see all columns in a wide DataFrame
import time
import numpy as np

In [2]:
# set the URLs for the dataframes
stats_23 = 'https://www.atptour.com/en/-/www/individualmatchstats/2023/all/all/Aces/percentage/desc/1/1000'
stats_24 = 'https://www.atptour.com/en/-/www/individualmatchstats/2024/all/all/Aces/percentage/desc/1/1000'

In [3]:
# get the stats api request
r23 = requests.get(url=stats_23).json()
r24 = requests.get(url=stats_24).json()

In [4]:
# put it to a dataframe and see the data
df23 = pd.DataFrame(r23['StatsList'])
df24 = pd.DataFrame(r24['StatsList'])
df23

,Number,PlayerId,LastName,FirstName,NatlId,PlayerHeadshotImageCmsUrl,PlayerScRelativeUrlPlayerProfile,PlayerScRelativeUrlPlayerCountryFlag,Percentage,Matches
0,"1,031",HB71,Hurkacz,Hubert,POL,/-/media/alias/player-headshot/hb71,/en/players/hubert-hurkacz/hb71/overview,/en/~/media/images/flags/pol.svg,0.00%,69
1,692,FB98,Fritz,Taylor,USA,/-/media/alias/player-headshot/fb98,/en/players/taylor-fritz/fb98/overview,/en/~/media/images/flags/usa.svg,0.00%,77
2,616,RE44,Rublev,Andrey,RUS,/-/media/alias/player-headshot/re44,/en/players/andrey-rublev/re44/overview,/en/~/media/images/flags/rus.svg,0.00%,82
3,613,Z355,Zverev,Alexander,GER,/-/media/alias/player-headshot/z355,/en/players/alexander-zverev/z355/overview,/en/~/media/images/flags/ger.svg,0.00%,80
4,547,TE51,Tsitsipas,Stefanos,GRE,/-/media/alias/player-headshot/te51,/en/players/stefanos-tsitsipas/te51/overview,/en/~/media/images/flags/gre.svg,0.00%,71
...,...,...,...,...,...,...,...,...,...,...
195,17,MH30,Millman,John,AUS,/-/media/alias/player-headshot/mh30,/en/players/john-millman/mh30/overview,/en/~/media/images/flags/aus.svg,0.00%,4
196,17,T0AP,Tseng,Chun-Hsin,TPE,/-/media/alias/player-headshot/t0ap,/en/players/chun-hsin-tseng/t0ap/overview,/en/~/media/images/flags/tpe.svg,0.00%,6
197,16,HD68,Harris,Billy,GBR,/-/media/alias/player-headshot/hd68,/en/players/billy-harris/hd68/overview,/en/~/media/images/flags/gbr.svg,0.00%,2
198,16,K0DP,Krutykh,Oleksii,UKR,/-/media/alias/player-headshot/k0dp,/en/players/oleksii-krutykh/k0dp/overview,/en/~/media/images/flags/ukr.svg,0.00%,3
199,16,D0CG,Diaz Acosta,Facundo,ARG,/-/media/alias/player-headshot/d0cg,/en/players/facundo-diaz-acosta/d0cg/overview,/en/~/media/images/flags/arg.svg,0.00%,6

In [8]:
# remove specific columns from both dataframes
columns_to_remove = ['PlayerHeadshotImageCmsUrl', 'PlayerScRelativeUrlPlayerProfile', 'PlayerScRelativeUrlPlayerCountryFlag']
df_cleaned_23 = df23.drop(columns=columns_to_remove)
df_cleaned_24 = df24.drop(columns=columns_to_remove)

In [9]:
# see cleaned dataframes
df_cleaned_23

    Number PlayerId     LastName  FirstName NatlId Percentage  Matches
0    1,031     HB71      Hurkacz     Hubert    POL      0.00%       69
1      692     FB98        Fritz     Taylor    USA      0.00%       77
2      616     RE44       Rublev     Andrey    RUS      0.00%       82
3      613     Z355       Zverev  Alexander    GER      0.00%       80
4      547     TE51    Tsitsipas   Stefanos    GRE      0.00%       71
..     ...      ...          ...        ...    ...        ...      ...
195     17     MH30      Millman       John    AUS      0.00%        4
196     17     T0AP        Tseng  Chun-Hsin    TPE      0.00%        6
197     16     HD68       Harris      Billy    GBR      0.00%        2
198     16     K0DP      Krutykh    Oleksii    UKR      0.00%        3
199     16     D0CG  Diaz Acosta    Facundo    ARG      0.00%        6

[200 rows x 7 columns]

In [10]:
# concatenate the dataframe to be organized by playerid
df_combined = pd.merge(df_cleaned_23, df_cleaned_24, on='PlayerId', how='outer', suffixes=('_23', '_24'))

In [11]:
# see the concatenated dataframe
df_combined

,Number_23,PlayerId,LastName_23,FirstName_23,NatlId_23,Percentage_23,Matches_23,Number_24,LastName_24,FirstName_24,NatlId_24,Percentage_24,Matches_24
0,NaN,A0CJ,NaN,NaN,NaN,NaN,NaN,0,Ajdukovic,Duje,CRO,0.00%,0.0
1,302,A0E2,Alcaraz,Carlos,ESP,0.00%,77.0,37,Alcaraz,Carlos,ESP,0.00%,9.0
2,167,A0FC,Arnaldi,Matteo,ITA,0.00%,31.0,98,Arnaldi,Matteo,ITA,0.00%,10.0
3,NaN,A0G8,NaN,NaN,NaN,NaN,NaN,0,Elsayed,Amr,EGY,0.00%,0.0
4,28,A0GC,Atmane,Terence,FRA,0.00%,4.0,25,Atmane,Terence,FRA,0.00%,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,33,Z09Z,Zhukayev,Beibit,KAZ,0.00%,3.0,NaN,NaN,NaN,NaN,NaN,NaN
247,22,Z0A1,Zeppieri,Giulio,ITA,0.00%,4.0,49,Zeppieri,Giulio,ITA,0.00%,4.0
248,613,Z355,Zverev,Alexander,GER,0.00%,80.0,147,Zverev,Alexander,GER,0.00%,14.0
249,213,Z371,Zhang,Zhizhen,CHN,0.00%,36.0,55,Zhang,Zhizhen,CHN,0.00%,11.0
250,73,Z419,Zapata Miralles,Bernabe,ESP,0.00%,41.0,10,Zapata Miralles,Bernabe,ESP,0.00%,7.0